### PR TITLE
Design updates

### LINKED ISSUE #134: Fix  pages design

### LINKED ISSUE #136: Use the same style for fonts

### LINKED ISSUE #138: Update button component

### PR DESCRIPTION
**Pull request by Klimonov**

### CODE REVIEW

**Review by EgoriusRus — APPROVED** [review]
LGTM

**Comment by EgoriusRus** [comment]
> LGTM
But need to fix
image

**Comment by Klimonov** [comment]
@EgoriusRus this is netlify issue. Will fix with @kezlya

**Review by kezlya — APPROVED** [review]
LGTM

**Pull request merged**
